### ISSUE TITLE
Review tracker 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1234]
The current `feedback` module on BreatheCode is capable of collecting NPS surveys to academy students on a recurrent basis, this new "Review" layer is built with the purpose of making sure that happy students leave a public review on the different review platforms.

When students are happy with the academy we should encourage them to leave a review on the different platforms like CareerKarma, CourseReport, SwitchUp, etc.

## Backend

- [x] There should be a DB model `ReviewPlatform` that contains all the review platforms: Career Karma, Switchup, etc. From each platform, we need its name, website URL and 4Geeks Landing Page URL.
- [ ] There should also be a ReivewTemplate object that contains: name, academy_owner, shared (boolean that denotes if its shared among academies), and content (the text we recommend for the review that is ideal to send to the student)
- [x] There is no need to POST, PUT or DELETE review platforms, only `GET /review/platform` to list all platforms.
- [ ] There is no need to POST, PUT or DELETE review templated, only `GET /review/template` to list all templated filtered by academy.
- [x] There should also be a DB model `Review` that contains all the information from ONE review: author_id, platform_id, score (from 1 to 5), status (PENDING, WAITING or COMPLETED)contacted_comment (the content of the message we send to the student asking for the review), author_comment (the review content), landing_page_url (URL that points to the review online), contacted_at (the date we contacted the student for review), reviewed_at (date and time that we received the review), updated_at (auto) and created_at (auto).
- [x] The moment a cohort is marked as "ENDED" a celery task is triggered that looks for its happy students (with 7 > NPS collected) and create one `Review` object for each of those students with 'PENDING' status and the platform_id is set to None, that way we know that the student has not yet completed one single review.
- [x] Reminder: Its easy to determine which happy students have not sent any reviews because they will have ONE review object with the platform_id null and the status=PENDING. We need to notify/remind the academy country manager every week to follow up with those students and ask for a review.
- [x] The endpoint to POST a new review should first look if there is a review with platform_id null and use that same object instead of creating a new one, if there are not Review objects for that student with platform_id null then it will create a new Review object.
- [ ] Update review: a review can be updated by ID.
             - If status is set to WAITING: The platform_id, template, or contacted_comment cannot be None.
             - If status is set to COMPLETED: no field can be null.
- [x] Get all reviews: There is an endpoint to get a list of all reviews and it can be filtered by status, platform, min_rating and max_rating, it can also be `sort` by rating and paginated, the endpoint returns a small version of the review.
- [ ] Get single review: I can get a review by ID and it returns the entire detail of the review.

## Front End

- [x] There should be a menu option inside the feedback module to list all the current reviews, filter and sort them.
- [ ] The list should be pre-filtered as default with PENDING reviews only.
- [ ] On the top of that list there should be a warning saying how many happy students have not yet reviewed the academy: "There are 23 happy students that have not yet reviewed the academy".
- [ ] The Country Manager is capable of updating a review with the correct information (chain the status or almost any other field) or create a new review.
- [ ] Bulk updated: The country manager is able mark the student testimonial reminder as "completed" using full actions from the list of reviews.
- [ ] When creating or updating a Review, the country manager can pick the template from a dropdown, also the template.
- [ ] In the dashboard, we need to include the review indicator with how many and the average rating for the academy.
