### ISSUE TITLE
SEO Errors - 12/7/2022

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#3814]
**Missing H1**

- [x] https://4geeksacademy.com/us/blog/career-growth       *Require implementation from Developer [case here](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3822)
- [x] https://4geeksacademy.com/us/blog/coding-bootcamps          *Require implementation from Developer [case here](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3836#issue-1490931341)
- [x] https://4geeksacademy.com/us/blog/learn-to-code        *Require implementation from Developer [case here](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3837#issue-1490940822)
- [x] https://4geeksacademy.com/us/blog/full-stack-developer             *Require implementation from Developer [case here](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3840#issue-1492220035)
- [x] https://4geeksacademy.com/us/geekpal-support       * ask Alejandro why the change was not implemented [image link](https://www.awesomescreenshot.com/image/35436653?key=24d91f2a91add641db8df685e2a4f779)
- [x] https://4geeksacademy.com/us/blog/trends-and-tech               *Require implementation from Developer [case here](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3841#issue-1492239702)
- [ ] https://4geeksacademy.com/us/why-4geeks     (beneficios de 4Geeks Academy)
- [ ] https://4geeksacademy.com/es/coding-bootcamps/curso-inteligencia-artificial

**Comment by Jsolis4geeks** [comment]
- [ ] https://4geeksacademy.com/us/privacy-policy
- [ ] https://4geeksacademy.com/us/blog/career-growth
- [ ] https://4geeksacademy.com/us/why-4geeks
- [ ] https://4geeksacademy.com/us/blog/coding-bootcamps
- [ ] https://4geeksacademy.com/us/blog/learn-to-code
- [ ] https://4geeksacademy.com/us/blog/full-stack-developer
- [ ] https://4geeksacademy.com/us/geekpal-support
- [ ] https://4geeksacademy.com/us/blog/trends-and-tech

**Comment by Jsolis4geeks** [comment]
**Pages Titles are duplicated**

- [ ] https://4geeksacademy.com/us/blog/career-growth
- [ ] https://4geeksacademy.com/us/why-4geeks
- [ ] https://4geeksacademy.com/us/blog/coding-bootcamps
- [ ] https://4geeksacademy.com/us/blog/learn-to-code
- [ ] https://4geeksacademy.com/us/blog/full-stack-developer
- [ ] https://4geeksacademy.com/us/blog/trends-and-tech
- [ ] https://4geeksacademy.com/us/career-growth/2019-developers-salaries-report
- [ ] https://4geeksacademy.com/us/coding-bootcamps/como-pagar-bootcamp-programacion
- [ ] https://4geeksacademy.com/us/career-growth/example-delete-me
- [ ] https://4geeksacademy.com/?lang=en
- [ ] https://4geeksacademy.com/

**Comment by Jsolis4geeks** [comment]
**Canonical Tag is missing**

- [ ] https://4geeksacademy.com/us/learn-to-code/javascript-and-python
- [ ] https://4geeksacademy.com/us/geeks-vs-others
- [ ] https://4geeksacademy.com/us/privacy-policy
- [ ] https://4geeksacademy.com/us/blog/career-growth
- [ ] https://4geeksacademy.com/us/learn-to-code/sample
- [ ] https://4geeksacademy.com/us/testimonials
- [ ] https://4geeksacademy.com/us/career-growth/how-to-prepare-for-a-typical-interview-for-web-development-position
- [ ] https://4geeksacademy.com/us/coding-bootcamps/internships-bootcamps-2021
- [ ] https://4geeksacademy.com/us/faq
- [ ] https://4geeksacademy.com/us/coding-bootcamps/software-engineer-bootcamp
- [ ] https://4geeksacademy.com/us/career-growth/hybrid-jobs
- [ ] https://4geeksacademy.com/us/coding-campus/europe-online-coding-bootcamp
- [ ] https://4geeksacademy.com/us/coding-bootcamps/are-coding-bootcamp-worth-it
- [ ] https://4geeksacademy.com/us/terms-conditions
- [ ] https://4geeksacademy.com/us/blog
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-caracas
- [ ] https://4geeksacademy.com/us/coding-bootcamps/part-time-bootcamps
- [ ] https://4geeksacademy.com/us/trends-and-tech/4geeks-academy-casimiro-global-foundation
- [ ] https://4geeksacademy.com/us/learn-to-code/hacks-learn-to-code
- [ ] https://4geeksacademy.com/us/coding-bootcamps/student-testimonials
- [ ] https://4geeksacademy.com/us/trends-and-tech/5-women-impacting-the-stem-industry
- [ ] https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer
- [ ] https://4geeksacademy.com/us/coding-bootcamp
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-mexico
- [ ] https://4geeksacademy.com/us/learn-to-code/web-development-versus-web-design
- [ ] https://4geeksacademy.com/us/the-academy
- [ ] https://4geeksacademy.com/us/career-growth/2019-developers-salaries-report
- [ ] https://4geeksacademy.com/us/financials
- [ ] https://4geeksacademy.com/us/why-4geeks
- [ ] https://4geeksacademy.com/us/contact
- [ ] https://4geeksacademy.com/us/trends-and-tech/becoming-a-web-developer-in-miami
- [ ] https://4geeksacademy.com/us/next-dates
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-costa-rica
- [ ] https://4geeksacademy.com/us/coding-bootcamps/what-kinds-of-jobs-do-coding-bootcamp-graduates-find-2
- [ ] https://4geeksacademy.com/us/partners
- [ ] https://4geeksacademy.com/us/landing/income-sharing-agreement
- [ ] https://4geeksacademy.com/us/awards
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-miami
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-uruguay
- [ ] https://4geeksacademy.com/us/trends-and-tech/4geeks-academy-history
- [ ] https://4geeksacademy.com/us/career-growth/free-games-to-practice-your-programming-skills
- [ ] https://4geeksacademy.com/us/trends-and-tech/miami-coding-programs-report
- [ ] https://4geeksacademy.com/us/coding-bootcamps/bootcamp-salaries-2-0
- [ ] https://4geeksacademy.com/us/coding-bootcamps/growth-road-full-time-job
- [ ] https://4geeksacademy.com/us/geekforce-career-support
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-argentina-buenos-aires
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-madrid
- [ ] https://4geeksacademy.com/?lang=en
- [ ] https://4geeksacademy.com/us/full-stack-developer/full-stack-web-development-at-miami-dade-college
- [ ] https://4geeksacademy.com/us/coding-bootcamps/machine-learning-engineering
- [ ] https://4geeksacademy.com/us/coding-bootcamps/why-we-teach-python-4geeks
- [ ] https://4geeksacademy.com/us/career-growth/7-hacks-to-land-a-job
- [ ] https://4geeksacademy.com/us/trends-and-tech/truth-behind-part-time-education
- [ ] https://4geeksacademy.com/us/learn-to-code/turnaround-education-traditions-4geeks-academy
- [ ] https://4geeksacademy.com/us/coding-bootcamps/pay-once-get-job-isa
- [ ] https://4geeksacademy.com/us/trends-and-tech/new-year-new-hiring-partners-launch-potato-us
- [ ] https://4geeksacademy.com/us/learn-to-code/used-backend-programming-language-miami
- [ ] https://4geeksacademy.com/us/coding-bootcamps/pay-tuition-4geeks
- [ ] https://4geeksacademy.com/us/trends-and-tech/part-time-future-education
- [ ] https://4geeksacademy.com/us/blog/coding-bootcamps
- [ ] https://4geeksacademy.com/us/learn-to-code/why-is-it-a-good-choice-to-become-a-software-developer
- [ ] https://4geeksacademy.com/us/learn-to-code/the-ideal-instructor
- [ ] https://4geeksacademy.com/us/coding-campus/online-coding-bootcamp
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-panama
- [ ] https://4geeksacademy.com/us/apply
- [ ] https://4geeksacademy.com/us/coding-bootcamps/choosing-coding-bootcamp
- [ ] https://4geeksacademy.com/us/coding-bootcamps/web-salaries-2017-coding-bootcamp
- [ ] https://4geeksacademy.com/us/blog/learn-to-code
- [ ] https://4geeksacademy.com/us/trends-and-tech/empowering-women-tech
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-colombia
- [ ] https://4geeksacademy.com/us/trends-and-tech/digital-marketing-in-the-coding-world
- [ ] https://4geeksacademy.com/us/trends-and-tech/women-in-tech-2017
- [ ] https://4geeksacademy.com/us/coding-bootcamps/como-pagar-bootcamp-programacion
- [ ] https://4geeksacademy.com/us/blog/full-stack-developer
- [ ] https://4geeksacademy.com/us/geekpal-support
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-bolivia
- [ ] https://4geeksacademy.com/us/learn-to-code/how-does-the-web-work-html-css
- [ ] https://4geeksacademy.com/us/career-growth/wages-report-2018-1
- [ ] https://4geeksacademy.com/us/coding-bootcamps/full-time-full-stack-developer
- [ ] https://4geeksacademy.com/us/learn-to-code/all-you-need-to-know-about-artificial-intelligence
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-orlando
- [ ] https://4geeksacademy.com/
- [ ] https://4geeksacademy.com/us/trends-and-tech/ama-chapter-of-fiu-4geeks-academy
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-santiago
- [ ] https://4geeksacademy.com/us/career-growth/web-developer-earn-the-salary-you-deserve
- [ ] https://4geeksacademy.com/us/blog/trends-and-tech
- [ ] https://4geeksacademy.com/us/cookies
- [ ] https://4geeksacademy.com/us/career-growth/example-delete-me
- [ ] https://4geeksacademy.com/us/trends-and-tech/4geeks-miami-dade-college-story
- [ ] https://4geeksacademy.com/us/coding-bootcamps/coding-bootcamp-syllabus-matters
- [ ] https://4geeksacademy.com/us/trends-and-tech/pay-tuition-4geeks-academy
- [ ] https://4geeksacademy.com/us/coding-bootcamps/pandemic-impact-on-coding-bootcamp
- [ ] https://4geeksacademy.com/us/coding-bootcamps/wyncode-ironhack-and-4geeks-academy-comparison
- [ ] https://4geeksacademy.com/us/trends-and-tech/dont-teach-nodejs-full-stack-development-program
- [ ] https://4geeksacademy.com/us/full-stack-developer/challenges-web-developer
- [ ] https://4geeksacademy.com/us/trends-and-tech/geekpal
- [ ] https://4geeksacademy.com/us/learn-to-code/python-one-of-the-most-in-demand-programming-languages
- [ ] https://4geeksacademy.com/us/full-stack-developer/4geeks-academy-teaches-php-backend-language
- [ ] https://4geeksacademy.com/us/trends-and-tech/skillsfund-4geeksacademy
- [ ] https://4geeksacademy.com/us/coding-bootcamps/the-talent-tree
- [ ] https://4geeksacademy.com/us/trends-and-tech/why-become-a-web-developer-in-miami-dade-in-2016
- [ ] https://4geeksacademy.com/us/coding-bootcamps/pre-work-phase-free-open-everybody
- [ ] https://4geeksacademy.com/us/coding-campus/coding-bootcamp-ecuador
- [ ] https://4geeksacademy.com/us/learn-to-code/rip-ruby-on-rails
- [ ] https://4geeksacademy.com/us/learn-to-code/should-i-learn-code
- [ ] https://4geeksacademy.com/us/trends-and-tech/launchcode-and-4geeks-academy
- [ ] https://4geeksacademy.com/us/learn-to-code/feelings-learning-coding

**Comment by Jsolis4geeks** [comment]
**URL Uppercase**

- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Screen-Shot-2018-11-06-at-3.53.12-PM.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2019/10/BLOG-5KEYAREAS-1024x524.jpg
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Testimonials.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Graficas-04.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2020/01/BLOG2.jpg
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/10/IMG-20180818-WA0019-300x225.jpg
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/01/Picture1.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/07/Screen-Shot-2018-07-16-at-3.51.05-PM-300x183.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2017/09/4GEEKS-ACADEMY-FULL.pdf
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/01/Picture12.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Graficas-03.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Graficas-07.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Students.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2020/01/BLOG1.jpg
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Placement.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/07/Mesa-de-trabajo-8-copia-2-1-1-300x300.jpg
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/07/Screen-Shot-2018-07-16-at-3.57.15-PM-300x209.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/11/Graficas-06.png
- [ ] https://4geeksacademy.com/static/images/blog/CSS.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2018/01/Picture1-1.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2017/10/4GA-Payment-Guidebook-2.pdf
- [ ] https://4geeksacademy.com/wp-content/uploads/2019/10/BLOG-BETTER-1024x524.jpg
- [ ] https://4geeksacademy.com/static/images/blog/CSS-game.png
- [ ] https://4geeksacademy.com/static/images/blog/JavaScript.png
- [ ] https://4geeksacademy.com/static/images/blog/SQL.png
- [ ] https://4geeksacademy.com/wp-content/uploads/2017/09/4GEEKS-ACADEMY-Syllabus-Program-Details.pdf
- [ ] https://4geeksacademy.com/wp-content/uploads/2017/09/4GEEKS-ACADEMY-SYLLABUS.pdf

**Comment by Jsolis4geeks** [comment]
- [ ] Sitemap Review

**Comment by Jsolis4geeks** [comment]
**4xx errors**

- [ ] https://4geeksacademy.com/static/images/blog/statista.png
- [ ] https://4geeksacademy.com/us/aprender-a-programar/facilidades-y-dificultades-para-aprender-a-programar
- [ ] https://4geeksacademy.com/us/aprender-a-programar/python-uno-de-los-lenguajes-de-programacion-mas-demandados
- [ ] https://4geeksacademy.com/us/aprender-a-programar/ventajas-de-trabajar-en-tecnologia
- [ ] https://4geeksacademy.com/us/learn-to-code/hacks-learn-to-code
- [ ] https://4geeksacademy.com/us/career-growth/wages-report-2018-1
- [ ] https://4geeksacademy.com/us/aprender-a-programar/juegos-gratis-para-practicar-tus-habilidades-de-programacion
- [ ] https://4geeksacademy.com/us/aprender-a-programar/nodejs-el-camino-hacia-el-exito-de-la-programacion-back-end
- [ ] https://4geeksacademy.com/us/aprender-a-programar/los-5-frameworks-fundamentales-para-frontend
- [ ] https://4geeksacademy.com/us/trends-and-tech/4geeks-academy-history
- [ ] https://4geeksacademy.com/us/career-growth/7-hacks-to-land-a-job
- [ ] https://4geeksacademy.com/es/software-engineer-salary/software-engineer-salary
- [ ] https://4geeksacademy.com/static/images/blog/sindrome-del-impostor.jpg
- [ ] https://4geeksacademy.com/static/images/blog/CSS.png
- [ ] https://4geeksacademy.com/es/full-stack/que-es-full-stack
- [ ] https://4geeksacademy.com/static/images/blog/Tecnologias_que_probablemente_van_a_adoptarse_para_el_ano_2025.jpg
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_22.png
- [ ] https://4geeksacademy.com/static/images/blog/blog_3.jpg
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/shutterstock_1663349944_1.png
- [ ] https://4geeksacademy.com/static/images/blog/facilidades-y-dificultades-para-aprender-a-programar-2.jpg
- [ ] https://4geeksacademy.com/static/images/blog/CSS-game.png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_19_(1).png
- [ ] https://4geeksacademy.com/static/images/blog/JavaScript.png
- [ ] https://4geeksacademy.com/static/images/blog/coding.png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Aprender_a_Programar.png
- [ ] https://4geeksacademy.com/static/images/blog/SQL.png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_15.png
- [ ] https://4geeksacademy.com/es/aprender-a-programar/javascript-and-python
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_10_(1).png
- [ ] https://4geeksacademy.com/static/images/blog/blog_2.jpg
- [ ] https://4geeksacademy.com/static/images/blog/coding-games.jpg

**Comment by Jsolis4geeks** [comment]
URL contains spaces

- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_22.png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/shutterstock_1663349944_1.png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_19_(1).png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Aprender_a_Programar.png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_15.png
- [ ] https://4geeksacademy.com/es/tendencias-y-tecnologia/De%20qué%20trata%20la%20Carrera%20de%20Programación%208debd1975a8743debdad4085020962d5/Blog_image_10_(1).png
