### ISSUE TITLE
Create table "website" to contribute fine tuning jobs

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4758]
- [ ] The website belongs to one or more topics for fine-tuning.
- [ ] When a new website is added to Rigobot, the user must specify to which topics it belongs to (one or more).
- [ ] Immediately after the website is added, a new task must trigger that downloads the body of the website and removes all HTML/CSS content from it, the only thing we will want are content within the following tags: span, p, divs, h1, h2, h6.
- [ ] There is a bulk action in the admin, that triggers a task to create completions from a particular website body, the completions will be create by leaving the question empty, remember to create all this completions on every topics that the website belongs to.

## Implementations notes:

Always create an actions that later will be called from the tasks, the should have the same name but the task will have `async_` prepended. For example here is [this action](https://github.com/breatheco-de/apiv2/blob/main/breathecode/authenticate/actions.py#L327) and [this task](https://github.com/breatheco-de/apiv2/blob/main/breathecode/authenticate/tasks.py#L27).

```
#actions.py
def create_complations_from_website(website_id):
```

```
# task.py
@shared_task
def async_create_complations_from_website(website_id):
     create_complations_from_website().
```
